apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-ingress
  namespace: rag-chatbot
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["rag.4.157.223.24.nip.io"]
      secretName: rag-tls
  rules:
    - host: "rag.4.157.223.24.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rag-ui
                port:
                  number: 80
